#!/usr/bin/env python3
"""Generate the deterministic release integrity manifest."""

from hashlib import sha256
from pathlib import Path
import sys


def release_paths(root: Path) -> list[Path]:
    paths = [
        root / "README.md",
        root / "LICENSE",
        root / "CHANGELOG.md",
        root / "docs/source-map.md",
        root / "docs/self-review.md",
        root / "adapters/install.sh",
        root / "adapters/uninstall.sh",
    ]
    paths.extend(sorted((root / "skill/omasafe-plugin-review").rglob("*")))
    return [
        path for path in paths
        if path.is_file() and "__pycache__" not in path.parts and path.suffix != ".pyc"
    ]


def main() -> int:
    root = Path(sys.argv[1] if len(sys.argv) > 1 else Path(__file__).resolve().parents[1]).resolve()
    lines = []
    for path in sorted(release_paths(root), key=lambda item: item.relative_to(root).as_posix()):
        digest = sha256(path.read_bytes()).hexdigest()
        lines.append(f"{digest}  {path.relative_to(root).as_posix()}")
    rendered = "# Generated by tests/generate_integrity.py; do not hand-edit.\n" + "\n".join(lines) + "\n"
    if "--stdout" in sys.argv[1:]:
        sys.stdout.write(rendered)
    else:
        (root / "SHA256SUMS").write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
